server.servlet.context-path=/@project.artifactId@/@project.version@
server.port=8100
spring.application.name=@project.artifactId@

# Muestreo: 1.0 = 100% (para auditoría)
management.tracing.sampling.probability=1.0

# Configuración OTLP
management.otlp.tracing.endpoint=http://localhost:4318/v1/traces
management.otlp.tracing.exporter.enabled=true
management.tracing.enabled=true

# Logs para depuración
logging.level.io.micrometer.tracing=DEBUG
logging.level.com.ov.telemetria=DEBUG